### ISSUE TITLE
Question of LLVM base version

### ISSUE THREAD

**Issue by Chan9Yan9** [cyruscyliu/videzzo-llvm-project#3]
Hello, I would like to study and research this project. I downloaded release 13.0.0 version of llvm-project from official GitHub and wanted to learn your work by using diff. However, I found that the diff results include many differences caused by the underlying LLVM version. If possible, could you please let me know which commit version of llvm-project you based your development on?

**Comment by cyruscyliu** [comment]
Hey, thank you for being interested. However, I could not find the exact commit.

**Comment by Chan9Yan9** [comment]
Well, thank you for your reply. I'll do some more research on my own.
